# Commands to start on workspace startup
tasks:
  - name: Initialize & Start Development Server
    init: npm run setup-auto_gpt && npm install 
    before: pip install -r auto_gpt/requirements.txt
    command: npm run dev

# Ports to expose on workspace startup
ports:
  - port: 7070
    onOpen: open-browser
    name: Frontend
    description: Frontend
  - port: 2200
    name: Backend
    description: Backend
